import { createBrowserRouter } from "react-router-dom";
import AppLayout from "@/layouts/AppLayout";
import {
  Dashboard,
  Projects,
  ProjectsActive,
  ProjectsLive,
  ProjectsFunded,
  MyProjects,
  Favorites,
  ProjectDetails,
  LenderRequestedDocuments,
  Municipalities,
  MunicipalDetails,
  MunicipalRatings,
  MunicipalAnalysis,
  QAManagement,
  MunicipalProjectProgress,
  ProjectProgressUpdate,
  MunicipalDocumentRequests,
  DocumentRequestUpload,
  AdminProjects,
  AdminProjectReview,
  AdminNotifications,
  AdminUsers,
  AdminReports,
  AdminCommitments,
  AdminCommitmentDetails,
  AdminInvitation,
  InvitationsManagement,
  Settings,
  NotFound,
  Landing,
  Login,
  Register,
  ForgotPassword,
  CardShowcase,
  CreateProject,
  MyDrafts,
  DataTableReference,
  RolesManagement,
  OrganizationsManagement,
  CommonMasterExcel,
} from "@/pages";

export const router = createBrowserRouter([
  {
    path: "/",
    element: <Landing />,
  },
  {
    path: "/login",
    element: <Login />,
  },
  {
    path: "/register",
    element: <Register />,
  },
  {
    path: "/forgot-password",
    element: <ForgotPassword />,
  },
  {
    path: "/main",
    element: <AppLayout />,
    children: [
      { index: true, element: <Dashboard /> },
      { path: "projects", element: <Projects /> },
      { path: "projects/live", element: <ProjectsLive /> },
      { path: "projects/funded", element: <ProjectsFunded /> },
      { path: "projects/my", element: <MyProjects /> },
      { path: "projects/favorites", element: <Favorites /> },
      { path: "projects/active", element: <ProjectsActive /> },
      { path: "projects/:id", element: <ProjectDetails /> },
      { path: "lender/requested-documents", element: <LenderRequestedDocuments /> },
      { path: "municipalities", element: <Municipalities /> },
      { path: "municipalities/:id", element: <MunicipalDetails /> },
      { path: "municipal/ratings", element: <MunicipalRatings /> },
      { path: "municipal/analysis", element: <MunicipalAnalysis /> },
      { path: "municipal/qa", element: <QAManagement /> },
      { path: "municipal/projects/progress", element: <MunicipalProjectProgress /> },
      { path: "municipal/projects/:id/progress/update", element: <ProjectProgressUpdate /> },
      { path: "municipal/document-requests", element: <MunicipalDocumentRequests /> },
      { path: "municipal/document-requests/:id/upload", element: <DocumentRequestUpload /> },
      { path: "admin/projects", element: <AdminProjects /> },
      // { path: "admin/projects/validate", element: <AdminProjects /> },
      { path: "admin/projects/validate/:id", element: <AdminProjectReview /> },
      
      { path: "admin/projects/create", element: <CreateProject /> },
      { path: "admin/projects/create/:draftId", element: <CreateProject /> },
      { path: "admin/projects/create/rejected/:projectId", element: <CreateProject /> },
      { path: "admin/projects/drafts", element: <MyDrafts /> },
      // removed AddParty route
      { path: "admin/notifications", element: <AdminNotifications /> },
      { path: "admin/users", element: <AdminUsers /> },
      { path: "admin/invitations", element: <InvitationsManagement /> },
      { path: "admin/invitation", element: <AdminInvitation /> },
      { path: "admin/reports", element: <AdminReports /> },
      { path: "admin/commitments", element: <AdminCommitments /> },
      { path: "admin/commitments/:projectReferenceId", element: <AdminCommitmentDetails /> },
      // Settings page now reads user details from auth session (useAuth), so no route param is needed
      { path: "settings", element: <Settings /> },
      { path: "demo", element: <Projects /> },
      { path: "designs/cards", element: <CardShowcase /> },
      { path: "components/datatable", element: <DataTableReference /> },
      { path: "master/roles", element: <RolesManagement /> },
      { path: "master/organizations", element: <OrganizationsManagement /> },
      { path: "master/common-excel", element: <CommonMasterExcel /> },
      { path: "*", element: <NotFound /> },
    ],
  },
  {
    path: "*",
    element: <NotFound />,
  },
]);


